// Run with: npx ts-node --project tsconfig.json scripts/seed-products.ts
// Seeds all Shopify products directly into the DB from MCP-fetched data
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const products = [
  {
    id: "12306429903166",
    handle: "duo-stone-ring",
    title: "Duo Stone Ring",
    description: "Two stones. One ring. One look that does more than expected. The Duo Stone Ring pairs two contrasting stones — different in shape, different in finish — on a slim gold band. Handcrafted sterling silver with gold plating. Sizes: Egyptian standard 6, 7, 8, 9.",
    priceMin: 1499,
    priceMax: 1499,
    currency: "EGP",
    tags: ["duo stone", "gift", "handmade", "jewelry", "ring", "silver", "sterling silver", "stone ring"],
    available: true,
    variants: ["6", "7", "8", "9"],
    productType: "Ring",
  },
  {
    id: "12306430165310",
    handle: "wave-cuff",
    title: "Wave Cuff",
    description: "Some pieces you put on and forget you're wearing. The Wave Cuff is one of them. Its soft, irregular wave silhouette wraps the wrist without pinching. Handcrafted sterling silver. One size fits most.",
    priceMin: 2299,
    priceMax: 2299,
    currency: "EGP",
    tags: ["bracelet", "cuff", "gift", "handmade", "jewelry", "silver", "sterling silver", "wave"],
    available: false,
    variants: ["One Size"],
    productType: "Bracelet",
  },
  {
    id: "12319497158974",
    handle: "mosaic-ring",
    title: "Mosaic Ring",
    description: "Color that doesn't shout — it glows. The Mosaic Ring wraps a full band in small colored stones, adding warmth and texture to any stack without overpowering it. Handcrafted sterling silver. Sizes: 6, 7, 8, 9.",
    priceMin: 1899,
    priceMax: 1899,
    currency: "EGP",
    tags: ["gift", "handmade", "jewelry", "mosaic", "ring", "silver", "sterling silver"],
    available: true,
    variants: ["6", "7", "8", "9"],
    productType: "Ring",
  },
  {
    id: "12319500009790",
    handle: "wave-ring",
    title: "Wave Ring",
    description: "Minimal doesn't mean plain. The Wave Ring proves that. A structured open ring shaped into a soft, irregular wave — it moves with your hand and sits flat. Handcrafted sterling silver. Sizes: 6, 7, 8, 9.",
    priceMin: 1599,
    priceMax: 1599,
    currency: "EGP",
    tags: ["gift", "handmade", "jewelry", "ring", "silver", "sterling silver", "wave"],
    available: true,
    variants: ["6", "7", "8", "9"],
    productType: "Ring",
  },
  {
    id: "12319526420798",
    handle: "dotted-ring",
    title: "Dotted Ring",
    description: "The best everyday ring is one you forget you're wearing — until someone asks about it. The Dotted Ring has a wider band with a soft dotted texture. Handcrafted sterling silver. Sizes: 6, 7, 8, 9.",
    priceMin: 1999,
    priceMax: 1999,
    currency: "EGP",
    tags: ["dotted", "gift", "handmade", "jewelry", "ring", "silver", "sterling silver"],
    available: true,
    variants: ["6", "7", "8", "9"],
    productType: "Ring",
  },
  {
    id: "12319542083902",
    handle: "twin-band-ring",
    title: "Twin Band Ring",
    description: "Small details make the biggest difference in a stack. The Twin Band Ring carries two green stones side by side on a delicate band — subtle enough not to overpower, distinctive enough to stand alone. Handcrafted sterling silver. Sizes: 6, 7, 8, 9.",
    priceMin: 1099,
    priceMax: 1099,
    currency: "EGP",
    tags: ["gift", "handmade", "jewelry", "ring", "silver", "sterling silver", "twin band"],
    available: true,
    variants: ["6", "7", "8", "9"],
    productType: "Ring",
  },
  {
    id: "12319550472510",
    handle: "sunray-earrings",
    title: "Sunray Earrings",
    description: "Earrings that frame the face without taking over it. The Sunray Earrings have a round form with a lined texture that catches light as you move. Available in Green, Red, and Blue stone options. Handcrafted sterling silver.",
    priceMin: 2699,
    priceMax: 2699,
    currency: "EGP",
    tags: ["earrings", "gift", "handmade", "jewelry", "silver", "sterling silver", "sunray"],
    available: true,
    variants: ["Green", "Red", "Blue"],
    productType: "Earrings",
  },
  {
    id: "12322920464702",
    handle: "arabesque-earrings",
    title: "Arabesque Earrings",
    description: "Not every stud needs to be plain to be wearable every day. The Arabesque Earrings carry an open-cut pattern across a gold surface — enough detail to make them interesting, minimal enough to wear with everything. Handcrafted sterling silver with gold plating.",
    priceMin: 1999,
    priceMax: 1999,
    currency: "EGP",
    tags: ["arabesque", "earrings", "gift", "handmade", "jewelry", "silver", "sterling silver"],
    available: true,
    variants: ["One Size"],
    productType: "Earrings",
  },
  {
    id: "12322924560702",
    handle: "wave-necklace",
    title: "Wave Necklace",
    description: "A necklace that moves the way you do. The Wave Necklace follows a soft, irregular wave shape that sits cleanly against the neckline — structured but never stiff. Handcrafted sterling silver.",
    priceMin: 5999,
    priceMax: 5999,
    currency: "EGP",
    tags: ["gift", "handmade", "jewelry", "necklace", "silver", "sterling silver", "wave"],
    available: true,
    variants: ["One Size"],
    productType: "Necklace",
  },
  {
    id: "12322927182142",
    handle: "ruby-cuff",
    title: "Ruby Cuff",
    description: "Color, structure, and ease — all in one bracelet. The Ruby Cuff is a slim open cuff finished with a stone on each end, giving it a clean and intentional look. Handcrafted sterling silver. One size fits most.",
    priceMin: 2399,
    priceMax: 2399,
    currency: "EGP",
    tags: ["bracelet", "cuff", "gift", "handmade", "jewelry", "ruby", "silver", "sterling silver"],
    available: false,
    variants: ["One Size"],
    productType: "Bracelet",
  },
  {
    id: "12322928361790",
    handle: "linear-cuff",
    title: "Linear Cuff",
    description: "Bold color. Clean structure. Zero effort to wear. The Linear Cuff features a row of blue stones across the front of a minimal open cuff — sharp and modern. Handcrafted sterling silver. One size fits most.",
    priceMin: 2899,
    priceMax: 2899,
    currency: "EGP",
    tags: ["bracelet", "cuff", "gift", "handmade", "jewelry", "linear", "silver", "sterling silver"],
    available: false,
    variants: ["One Size"],
    productType: "Bracelet",
  },
  {
    id: "12322930164030",
    handle: "ridge-ring",
    title: "Ridge Ring",
    description: "Texture changes everything. The Ridge Ring takes a full band and gives it depth — a ridged surface that catches light differently depending on how you hold your hand. Handcrafted sterling silver. Sizes: 6, 7, 8, 9.",
    priceMin: 2299,
    priceMax: 2299,
    currency: "EGP",
    tags: ["gift", "handmade", "jewelry", "ridge", "ring", "silver", "sterling silver"],
    available: true,
    variants: ["6", "7", "8", "9"],
    productType: "Ring",
  },
  {
    id: "12322939601214",
    handle: "trio-stone-ring",
    title: "Trio Stone Ring",
    description: "Three stones. One slim band. A lot of personality for a small piece. The Trio Stone Ring lines up three blue stones in a clean row — balanced and precise. Handcrafted sterling silver. Sizes: 6, 7, 8, 9.",
    priceMin: 1299,
    priceMax: 1299,
    currency: "EGP",
    tags: ["gift", "handmade", "jewelry", "ring", "silver", "sterling silver", "trio stone"],
    available: true,
    variants: ["6", "7", "8", "9"],
    productType: "Ring",
  },
  {
    id: "12322943172926",
    handle: "signet-ring",
    title: "Signet Ring",
    description: "Some rings make a statement. The Signet Ring simply commands respect. A polished gold surface, a solid silhouette, and a weight that feels intentional. Handcrafted sterling silver with gold plating. Sizes: 6, 7, 8, 9.",
    priceMin: 2099,
    priceMax: 2099,
    currency: "EGP",
    tags: ["gift", "handmade", "jewelry", "ring", "signet", "silver", "sterling silver"],
    available: true,
    variants: ["6", "7", "8", "9"],
    productType: "Ring",
  },
  {
    id: "12322945204542",
    handle: "marquise-ring",
    title: "Marquise Ring",
    description: "The marquise cut was made for people who want something different. The Marquise Ring sets a bold, elongated blue stone on a clean gold band — sharper, more graphic, and more eye-catching than a standard round stone. Handcrafted sterling silver. Sizes: 6, 7, 8, 9.",
    priceMin: 1699,
    priceMax: 1699,
    currency: "EGP",
    tags: ["gift", "handmade", "jewelry", "marquise", "ring", "silver", "sterling silver"],
    available: true,
    variants: ["6", "7", "8", "9"],
    productType: "Ring",
  },
  {
    id: "12322950840638",
    handle: "mini-band-ring",
    title: "Mini Band Ring",
    description: "The ring you never take off. The Mini Band Ring is slim, light, and finished with a small green stone that adds just enough color to make it more than plain. Perfect for stacking. Handcrafted sterling silver. Sizes: 6, 7, 8, 9.",
    priceMin: 899,
    priceMax: 899,
    currency: "EGP",
    tags: ["gift", "handmade", "jewelry", "mini band", "ring", "silver", "sterling silver"],
    available: true,
    variants: ["6", "7", "8", "9"],
    productType: "Ring",
  },
  {
    id: "12322952708414",
    handle: "core-ring",
    title: "Core Ring",
    description: "Classic shape. Fresh color. Instant combination. The Core Ring puts a round green stone at the center of a clean gold band — familiar in form but elevated in finish. Handcrafted sterling silver with gold plating. Sizes: 6, 7, 8, 9.",
    priceMin: 1399,
    priceMax: 1399,
    currency: "EGP",
    tags: ["core ring", "gift", "handmade", "jewelry", "ring", "silver", "sterling silver"],
    available: true,
    variants: ["6", "7", "8", "9"],
    productType: "Ring",
  },
  {
    id: "12322953920830",
    handle: "emerald-cut-ring",
    title: "Emerald Cut Ring",
    description: "Sharp. Defined. Quietly confident. The Emerald Cut Ring centers a rectangular green stone on a gold band — a cut that's more geometric, more intentional. Handcrafted sterling silver with gold plating. Sizes: 6, 7, 8, 9.",
    priceMin: 1499,
    priceMax: 1499,
    currency: "EGP",
    tags: ["emerald cut", "gift", "handmade", "jewelry", "ring", "silver", "sterling silver"],
    available: true,
    variants: ["6", "7", "8", "9"],
    productType: "Ring",
  },
  {
    id: "12367494676798",
    handle: "wave-set",
    title: "Wave Set",
    description: "Two pieces. One aesthetic. The Wave Set pairs the Wave Ring and the Wave Cuff — both shaped around the same soft wave silhouette. Worn together, they just make sense. Handcrafted sterling silver. Ring sizes: 6, 7, 8, 9.",
    priceMin: 3799,
    priceMax: 3799,
    currency: "EGP",
    tags: ["bundle", "cuff", "gift", "handmade", "jewelry", "ring", "set", "silver", "sterling silver", "wave set"],
    available: false,
    variants: ["6", "7", "8", "9"],
    productType: "Set",
  },
  {
    id: "12399918514494",
    handle: "stack-pack-ridge-ring-dotted-ring-mini-band-ring",
    title: "Stack Pack — Ridge Ring, Dotted Ring & Mini Band Ring",
    description: "Three rings. One complete stack. Designed to be worn together. The Stack Pack pairs the Ridge Ring, the Dotted Ring, and the Mini Band Ring — three different textures that layer perfectly. Handcrafted sterling silver. Sizes: 6, 7, 8.",
    priceMin: 4299,
    priceMax: 4299,
    currency: "EGP",
    tags: ["bundle", "gift", "handmade", "jewelry", "ring", "set", "silver", "sterling silver", "stack"],
    available: false,
    variants: ["6", "7", "8"],
    productType: "Set",
  },
  {
    id: "12399918612798",
    handle: "stone-collection-mosaic-ring-core-ring-trio-stone-ring",
    title: "Stone Collection — Mosaic Ring, Core Ring & Trio Stone Ring",
    description: "Three stone rings. One collection. The Stone Collection brings together the Mosaic Ring, the Core Ring, and the Trio Stone Ring — three stone rings with different personalities that work together. Handcrafted sterling silver. Sizes: 6, 7, 8.",
    priceMin: 4699,
    priceMax: 4699,
    currency: "EGP",
    tags: ["bundle", "gift", "handmade", "jewelry", "ring", "set", "silver", "sterling silver", "stone"],
    available: false,
    variants: ["6", "7", "8"],
    productType: "Set",
  },
  {
    id: "12400524984638",
    handle: "the-statement-3-dotted-ring-ridge-ring-signet-ring",
    title: "The Statement Three — Dotted Ring, Ridge Ring & Signet Ring",
    description: "Three rings. One image. The exact stack from our editorial shoot. The Dotted Ring adds texture, the Ridge Ring brings structure, and the Signet anchors it all. Handcrafted sterling silver. Sizes: 6, 7, 8.",
    priceMin: 5299,
    priceMax: 5299,
    currency: "EGP",
    tags: ["bundle", "gift", "handmade", "jewelry", "ring", "set", "silver", "sterling silver", "statement"],
    available: false,
    variants: ["6", "7", "8"],
    productType: "Set",
  },
];

async function main() {
  console.log(`Seeding ${products.length} products...`);

  for (const p of products) {
    const rawJson = {
      id: parseInt(p.id),
      title: p.title,
      handle: p.handle,
      product_type: p.productType,
      tags: p.tags.join(", "),
      body_html: p.description,
      variants: p.variants.map((v, i) => ({
        id: i,
        title: v,
        price: String(p.priceMin),
        sku: "",
        inventory_quantity: p.available ? 1 : 0,
        inventory_item_id: i,
      })),
      images: [],
      vendor: "RB Jewelry",
      status: "active",
    };

    await prisma.shopifyProductCache.upsert({
      where: { id: p.id },
      update: {
        handle: p.handle,
        title: p.title,
        description: p.description,
        priceMin: p.priceMin,
        priceMax: p.priceMax,
        currency: p.currency,
        tags: p.tags,
        available: p.available,
        rawJson,
        syncedAt: new Date(),
      },
      create: {
        id: p.id,
        handle: p.handle,
        title: p.title,
        description: p.description,
        priceMin: p.priceMin,
        priceMax: p.priceMax,
        currency: p.currency,
        tags: p.tags,
        available: p.available,
        rawJson,
      },
    });
    console.log(`  ✓ ${p.title}`);
  }

  console.log(`\nDone! ${products.length} products seeded.`);
  await prisma.$disconnect();
}

main().catch((e) => {
  console.error(e);
  prisma.$disconnect();
  process.exit(1);
});
