-- Enable Row-Level Security on all tables to block public access via Supabase REST API.
-- Prisma connects as the postgres superuser (BYPASSRLS), so this does not affect the app.

ALTER TABLE "User" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Conversation" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Message" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AiReply" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AiConfig" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ShopifyConfig" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "InstagramComment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ShopifyProductCache" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ShopifyOrderCache" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "WebhookEvent" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PushSubscription" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "InventoryItem" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AppSettings" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Expense" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ShareholderInvestment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "DailyReport" ENABLE ROW LEVEL SECURITY;
